### ISSUE TITLE
Migrate repository to sile-typesetter Github org?

### ISSUE THREAD

**Issue by alerque** [sile-typesetter/cassowary.lua#13]
This one is less obvious than [sile](https://github.com/sile-typesetter/sile/issues/666) and [libtexpdf](https://github.com/simoncozens/libtexpdf/issues/10) and certainly not required but this could also be kept alongside [SILE](https://github.com/sile-typesetter/sile) in the [`sile-typesetter`](https://github.com/sile-typesetter/sile) org. As I understand it the Lua module was first started as a helper for SILE, where it is a pretty settled requirement, and probably it's most active 'user'. I might not be a bad candidate to keep under that nasmespace as well. It won't restrict anybody using the Lua module independently.

**Comment by tst2005** [comment]
What ?
Where did you see relation between cassowary.lua and the projects you mentioned ?

**Comment by alerque** [comment]
Just a hunch. The root commit e2c77d0f273086d903a998c9c8761dc48bbc27cf of this repo was in June of 2014. That's right about the time the TODO list in the SILE source repository [gained an entry](https://github.com/sile-typesetter/sile/commit/09e5026) called "port cassowary". My inference was that those two things were related. I'm sure @simoncozens can set the record straight on how he sees the relation, if any.

**Comment by simoncozens** [comment]
I don't see a downside, and if it makes the maintenance more sustainable, let's do it.
