### ISSUE TITLE
Need a new release

### ISSUE THREAD

**Issue by alerque** [sile-typesetter/cassowary.lua#30]
In [44 commits since the last release](https://github.com/sile-typesetter/cassowary.lua/compare/v2.2...master) almost nothing has changed in the substance of this library, but a lot has changed in the form. I'm working on getting downstream distro packaging cleaned up for this and there are quite a few issues (e.g. missing license) that would be resolved if we could tag and release a point release to Luarocks.

I'd be happy to handle the GitHub half, but per previous discussions ([see Gitter here](https://gitter.im/sile-typesetter/sile?at=5f6e36116e85e0058c55ab7e)) LuaRocks doesn't play nicely with teams yet and @simoncozens you are the one with access there right now.

**Comment by alerque** [comment]
I'm happy to do the Git end of things if you want, just let me know.

We *could* do a patch version bump `v2.2.1` but I tend to think a minor bump to `v2.3` is probably justified.

**Comment by simoncozens** [comment]
I think I've done this.

**Comment by alerque** [comment]
Um ... yes. But next time the rockspecs folder should get a copy of the rockspec *before* tagging the release, but not after. Yes Luarock packaging is crazy pants. Yes there is talk of fixing it, but it's not easy to transition.

I'll fix the missing rockspec. For Arch packaging it won't batter because even the stable packaging is using the SCM rockspec at time of release tagging, but other distros might care about this. We'll have to see what Homebrew does, we might need to do a `-2` rockrel to fix this.

**Comment by alerque** [comment]
Follow up: I see now the trouble was you tagged on a branch instead of `master` — an easily fixable issue.

**Comment by alerque** [comment]
Hey Simon other than the bogus content of the rockspec (see #32) I think the rest of the release process went fine. I bumped the tag here, can you fetch that and do the Luarocks publish part again please? Thanks!

**Comment by simoncozens** [comment]
Sorry about this. I hadn't twigged the repo change. I've uploaded the new rockspec.

Is it worth making a CI action on GitHub release? That way I can stash the api key as a secret and anyone with maintainer access can push a release to luarocks?

**Comment by alerque** [comment]
Sure that would work. I'll fiddle with that next time I get a chance.
